import { useState, useEffect } from 'react';
import {
    collection,
    query,
    onSnapshot,
    addDoc,
    deleteDoc,
    doc,
    updateDoc
} from 'firebase/firestore';
import type { DocumentData } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { useAuth } from '../context/AuthContext';

export const useFirestore = <T extends { id?: string }>(collectionName: string) => {
    const [data, setData] = useState<T[]>([]);
    const [loading, setLoading] = useState(true);
    const { user } = useAuth();

    useEffect(() => {
        if (!user) {
            setData([]);
            setLoading(false);
            return;
        }

        const colRef = collection(db, 'users', user.uid, collectionName);
        const q = query(colRef);

        const unsubscribe = onSnapshot(q, (snapshot) => {
            const items: T[] = [];
            snapshot.forEach((doc) => {
                items.push({ id: doc.id, ...doc.data() } as T);
            });
            setData(items);
            setLoading(false);
        }, (error) => {
            console.error(`Error fetching ${collectionName}:`, error);
            setLoading(false);
        });

        return () => unsubscribe();
    }, [user, collectionName]);

    const add = async (item: any) => {
        if (!user) return;
        try {
            const colRef = collection(db, 'users', user.uid, collectionName);
            // If the item already has an ID (e.g. uuid generated locally), we can use it?
            // Firestore auto-generates IDs if we use addDoc.
            // If we want to preserve local IDs or specific IDs, we use setDoc.
            // For simplicity, let's let Firestore generate IDs for now or strip the local ID if it exists?
            // Actually, best practice often is to let Firestore generate the ID.
            // But if our app logic relies on specific IDs generated by crypto.randomUUID(), we might want to keep that flow or adapt it.
            // `addDoc` returns a ref with the new ID.

            // Let's strip the 'id' from the item payload to avoid duplication in the doc data, 
            // unless we specifically want it there.
            const { id, ...rest } = item;
            await addDoc(colRef, rest);
        } catch (error) {
            console.error(`Error adding to ${collectionName}:`, error);
            throw error;
        }
    };

    const remove = async (id: string) => {
        if (!user) return;
        try {
            const docRef = doc(db, 'users', user.uid, collectionName, id);
            await deleteDoc(docRef);
        } catch (error) {
            console.error(`Error removing from ${collectionName}:`, error);
            throw error;
        }
    };

    const update = async (id: string, updates: Partial<T>) => {
        if (!user) return;
        try {
            const docRef = doc(db, 'users', user.uid, collectionName, id);
            await updateDoc(docRef, updates as DocumentData);
        } catch (error) {
            console.error(`Error updating ${collectionName}:`, error);
            throw error;
        }
    };

    return { data, add, remove, update, loading };
};
