import {
    Sprout,
    Trophy,
    PiggyBank,
    Footprints,
    Upload,
    Flame,
    Eye,
    Scroll,
    Moon,
    Crosshair,
    ShieldCheck,
    Gem,
    Infinity as InfinityIcon,
    Crown,
    CreditCard,
    Hammer,
    Shield,
    Lock,
    Sparkles,
    Compass,
    TrendingUp,
    ShieldAlert,
    X,
    CheckCircle
} from 'lucide-react';

export const GAMIFICATION_ICONS: Record<string, React.ComponentType<any>> = {
    Sprout,
    Trophy,
    PiggyBank,
    Footprints,
    Upload,
    Flame,
    Eye,
    Scroll,
    Moon,
    Crosshair,
    ShieldCheck,
    Gem,
    Infinity: InfinityIcon,
    Crown,
    CreditCard,
    Hammer,
    Shield,
    Lock,
    Sparkles,
    Compass,
    TrendingUp,
    ShieldAlert,
    X,
    CheckCircle
};
